# Generated by Django 5.0.3 on 2024-04-01 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DATA_WORKER',
            fields=[
                ('WORKER_ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('WORKER_NAME', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DATA_IMAGE',
            fields=[
                ('IMAGE_ID', models.AutoField(primary_key=True, serialize=False)),
                ('IMAGE', models.CharField(max_length=200)),
                ('DATE_WORK', models.DateField(auto_now=True)),
                ('STATUS', models.CharField(max_length=1, null=True)),
                ('WORKER_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.data_worker')),
            ],
        ),
        migrations.CreateModel(
            name='QUESTION',
            fields=[
                ('QUESTION_ID', models.AutoField(primary_key=True, serialize=False)),
                ('QUESTION', models.CharField(max_length=1000)),
                ('QUESTION_CNT', models.IntegerField()),
                ('STATUS', models.CharField(max_length=1, null=True)),
                ('IMAGE_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.data_image')),
            ],
        ),
        migrations.CreateModel(
            name='ANSWER',
            fields=[
                ('ANSWER_ID', models.AutoField(primary_key=True, serialize=False)),
                ('ANSWER', models.CharField(max_length=1000)),
                ('STATUS', models.CharField(max_length=1, null=True)),
                ('QUESTION_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.question')),
            ],
        ),
    ]
