# Generated by Django 5.0.3 on 2024-05-02 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='STATUS',
        ),
        migrations.RemoveField(
            model_name='question',
            name='STATUS',
        ),
    ]
